#host: IP_Address
#------ This .yml file is Ansible Playbook --------#
#------ Play 1 Starts --------#
- hosts: all
  tasks:
    - package: "name=httpd state=present"
    - copy: "src=home.html dest=/var/www/html/"
    - service: "name=httpd state=started"

#------ Play 1 Ended --------#
